apiVersion: devx.ibm.com/v1alpha1
kind: StarterKit
metadata:
  name: watson-starterkit
spec:
  templateRepo:
    templateOwner: IBM
    templateRepoName: speech-to-text-code-pattern
    owner: jmeis
    name: stt-starterkit
    repoDescription: "my cool watson repo"
    secretKeyRef:
      name: tokenName
      key: tokenKey
  options:
    port: 5000
    env:
    - name: SPEECH_TO_TEXT_URL
      valueFrom:
        secretKeyRef:
          name: stt-starterkit
          key: url
    - name: SPEECH_TO_TEXT_APIKEY
      valueFrom:
        secretKeyRef:
          name: stt-starterkit
          key: apikey
