kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: starter-kit-operator
subjects:
- kind: ServiceAccount
  name: starter-kit-operator
  namespace: placeholder
roleRef:
  kind: ClusterRole
  name: starter-kit-operator
  apiGroup: rbac.authorization.k8s.io
